<foot>
	<?php
		load_js(array(
			"assets/js/jquery-3.3.1.min.js",
			"assets/js/bootstrap.min.js",
			"assets/js/player.js",
			"assets/js/jquery.nice-select.min.js",
			"assets/js/mixitup.min.js",
			"assets/js/jquery.slicknav.js",
			"assets/js/owl.carousel.min.js",
			"assets/js/main.js",
			"assets/js/movie.js",
		))
	?>
</foot>
